configuration:
  projectName : Asset Lifecycle Manager
redis:
   service : rmd_redis_trilokee_gupta
   cacheExpirationtime : 300
postgres:
   service : postgresql_diane_zhen
   
spring:
   oauth2:
     resource: 
       userInfoUri: https://04442ad5-53db-4a3d-ae49-8c0d12e2d907.predix-uaa.run.aws-usw02-pr.ice.predix.io/login